### ISSUE TITLE
Regex Validation Rule - Alternation Support

### ISSUE THREAD

**Issue by BlackBeltPanda** [formr/Formr#106]
Regex alternation currently doesn't work due to the pipe character splitting the regex validation rules. See: [https://r.je/php-explode-split-with-escape-character](https://r.je/php-explode-split-with-escape-character).

**Comment by timgavin** [comment]
Good catch!

Here's a suggestion, Please try this and let me know if it works for you.

The delimiters are a private property, defined on line 157 in `class.formr.php`. The validation rule delimiter is the second value in the array.

Go to line 157 and change `private` to `public`

```
public $delimiter = array(',', '|');
```

Then in your form, add the delimiter property and assign the character you want to use as your delimiter as the second value in the array. In this example I changed it to a comma.

```
$form->delimiter = [',', ','];
```

Now just use a comma instead of a pipe as your rules delimiter.

```
if($form->submitted()) {
    $name = $form->post('name', '', 'min[3],regex[/foo|bar/]');
}
```

Does this seem like a good solution to you?

**Comment by BlackBeltPanda** [comment]
It can certainly work for what I need but it's not very future-proof since it would break on any regex using commas (or whatever delimiter I decide to use). For the time being, I just applied the fix in the article I linked above and that did the trick quite well. =)

**Comment by timgavin** [comment]
Next release will allow for validation rules to be passed as an array. Appreciate you pointing this out!

```php
if($form->submitted()) {
    $name = $form->post('name', '', ['min[3]', 'max[5]', 'not_regex[/foo|bar/]']);
}
```

It's a pretty easy fix, so if you want to take advantage of this now, just go to line 2119 and change this

```php
# separate the rules
$rules = explode($this->delimiter[1], $rules);
```

To this

```php
# validation rules are a string; let's put them into an array
if(! is_array($rules)) {
    $rules = explode($this->delimiter[1], $rules);
}
```
