### ISSUE TITLE
Labels still output from text inputs automatically even with forms instantiated with hush

### ISSUE THREAD

**Issue by thinkcube-solutions** [formr/Formr#107]
Hello! I just wanted to pass along something I came across.

When you are creating inputs, if you pass label text as a second parameter the inputs will automatically echo even with the hush option added to the Formr class constructor.

Example that stores the generated input properly into a variable

```
$form = new Formr\Formr('', 'hush');
$input = $form->text('example_text_field');
```

Example that does not store the input to the variable and automatically echos/outputs immediately.

```
$form = new Formr\Formr('', 'hush');
$input = $form->text('example_text_field', 'Example Label');
```

**Comment by timgavin** [comment]
Good catch, thanks. I missed a couple of instances in the default wrapper; this will be fixed in the next release.

if you want to fix your version, just open `lib/class.formr.wrappers.php` and find any function that is `$this->function()` and replace it with `$this->formr->function()`. I think there's only one or two that are missing it.

So this
```
$this->label($data)
```

Becomes this
```
$this->formr->label($data)
```

**Comment by thinkcube-solutions** [comment]
You're welcome! Thanks again for an incredible library. It has been invaluable over the years.
