### ISSUE TITLE
No output from flash messages in 'hush' mode

### ISSUE THREAD

**Issue by ameotoko** [formr/Formr#119]
Flash messages seem to be incompatible with `'hush'` mode, because the block below does not return any html:

https://github.com/formr/Formr/blob/29fb4424c6a5691f5ee9e0e9b26a67aa1865c45a/class.formr.php#L1482-L1503

I'll provide a PR (hopefully I got the logic of your method right).

**Comment by timgavin** [comment]
Please show an example of your code, as messages are printing just fine for me in hush mode.

Edit: it's been a long time since I implemented flash messages so my memory is pretty gray in this area... looking through the code I'm not sure I'm even using them anymore. I've looked through the documentation and don't see anything on flash messages either. So I'm curious as to what you're doing because I don't remember anything about it lol

**Comment by ameotoko** [comment]
The good practice is to reload the page once again after processing the POST request from the submitted form. Otherwise, if user refreshes the page (e.g. by pressing F5) – the browser will repeat POST request. That's where we need flash messages.

Here's the simplest example, outlining the steps:

```php
session_start();

$form = new \Formr\Formr('', 'hush');

$buffer = '';

if ($form->submitted()) {

    // 2. Process the POST request
    if ($form->ok()) {
        $form->success_message('Form was successfully submitted.', 'Thank you!', true);

        // 3. Reload the page
        header('Location: ' . $_SERVER['PHP_SELF']);
    }
}

// 4. User should see the flash message here
$buffer .= $form->messages();

// 1. Show the form
$buffer .= $form->open();
$buffer .= $form->text('name', 'Name');
$buffer .= $form->email('email', 'E-mail');
$buffer .= $form->submit_button();
$buffer .= $form->close();

echo $buffer;
```

With the current implementation, there is no output at step 4. My PR fixes it

**Comment by timgavin** [comment]
Okay I see what's happening, and why it's not working. Your PR is close, but the main problem is that I just didn't think this through. The flash messages still won't print in your PR because of the following lines, which obviously removes the flash messages from the session. 🤦‍♂️

```php
$_SESSION['formr']['flash'] = NULL;
unset($_SESSION['formr']['flash']);
```

These actually need to be placed **after** you echo the `$buffer`

```php
echo $buffer;

$_SESSION['formr']['flash'] = NULL;
unset($_SESSION['formr']['flash']);
```

So I'll figure out a more elegant way to handle this. In the mean time if you incorporate that, and your PR (commenting out those lines) then it should work for you.

FWIW you can also use the [`clear()`](https://formr.github.io/methods/#clear) method to clear the contents of the form instead of refreshing the page

**Comment by timgavin** [comment]
Okay I see what's happening, and why it's not working. Your PR is close, but the main problem is that I just didn't think this through. The flash messages still won't print in your PR because of the following lines, which obviously removes the flash messages from the session. 🤦‍♂️

```php
$_SESSION['formr']['flash'] = NULL;
unset($_SESSION['formr']['flash']);
```

These actually need to be placed **after** you echo the `$buffer`

```php
echo $buffer;

$_SESSION['formr']['flash'] = NULL;
unset($_SESSION['formr']['flash']);
```

So I'll figure out a more elegant way to handle this. In the mean time if you incorporate that, and your PR (commenting out those lines) then it should work for you.

FWIW you can also use the [`clear()`](https://formr.github.io/methods/#clear) method to clear the contents of the form instead of refreshing the page

**Comment by ameotoko** [comment]
> The flash messages still won't print in your PR

it works though, just test my snippet against master branch and my branch, you’ll see the difference. 

> the following lines, which obviously removes the flash messages from the session. 🤦‍♂️

It doesn’t matter, because in `messages()`, the content of `$_SESSION` is saved to a variable before that, and it’s the content of the variable that gets returned, not `$_SESSION` directly. 


> I just didn't think this through

Actually, it doesn’t seem so – judging by other fragments of that method, the logic is similar. It just seems that you forgot to return the output😊 But I might be wrong, of course. 

> FWIW you can also use the `clear()` method to clear the contents of the form instead of refreshing the page

It only resets `$_POST`, but I still prefer not to keep user’s browser open on a `POST` request. Just a precaution 😊

**Comment by timgavin** [comment]
> it works though, just test my snippet against master branch and my branch, you’ll see the difference.

I have. I copied your code and made the edits from your PR and I do not see a success message after a successful submission. if you put `$form->dump($_SESSION);` after `echo $buffer;` (or anywhere, really) you'll see that the flash session isn't even set.

> It doesn’t matter, because in messages(), the content of $_SESSION is saved to a variable before that, and it’s the content of the variable that gets returned, not $_SESSION directly.

That's what I thought too, but then I ran some tests and dumped the SESSION in different methods and found out that flash is being erased.

Or perhaps I'm overlooking something? In your PR it looks like you only modified 4 lines and added one. Am I wrong?

Edit: Your PR is on the right track, and I appreciate you pointing this out and submitting it!

**Comment by ameotoko** [comment]
Are you sure the session is started at the top of the snippet? `session_start()`

**Comment by timgavin** [comment]
Here's what I'm using.

```php
<?php
session_start();
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
require 'Formr/class.formr.php';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
</head>
<body style="padding:60px">
<?php

  $form = new \Formr\Formr('bootstrap', 'hush');
  
  $buffer = '';
  
  $form->dump($_SESSION);
  
  if ($form->submitted()) {
    
    $name = $form->post('name','','min[3]');
  
      // 2. Process the POST request
      if ($form->ok()) {
          $form->success_message('Form was successfully submitted.', 'Thank you!', true);
  
          // 3. Reload the page
          header('Location: ' . $_SERVER['PHP_SELF']);
      }
  }
  
  // 4. User should see the flash message here
  $buffer .= $form->messages();
  
  // 1. Show the form
  $buffer .= $form->open();
  $buffer .= $form->text('name', 'Name');
  $buffer .= $form->email('email', 'E-mail');
  $buffer .= $form->submit_button();
  $buffer .= $form->close();
  
  echo $buffer;
  
  // $_SESSION['formr']['flash'] = NULL;
  // unset($_SESSION['formr']['flash']);
?>
</body>
</html>
```

**Comment by ameotoko** [comment]
Please also add `exit;` statement after `header()`, like this:

```php
// 2. Process the POST request
if ($form->ok()) {
    $form->success_message('Form was successfully submitted.', 'Thank you!', true);
 
    // 3. Reload the page
    header('Location: ' . $_SERVER['PHP_SELF']);
    exit;
}
```

I had the same problem when testing, but somehow this line slipped from the snippet again…

**Comment by timgavin** [comment]
You can now use `redirect()` more efficiently

Instead of this

```php
header('Location: ' . $_SERVER['PHP_SELF']);
exit;
```

You can do this

```php
$form->redirect('self');
```

Thanks again for the PR!
