### ISSUE TITLE
Inline radio buttons with Bulma framework

### ISSUE THREAD

**Issue by janstieler** [formr/Formr#121]
Hi,
is there a possibility to get inlined radio buttons with Bulma Framework? If I use `radio_inline` with Bulma it doesn't work.
Like here https://bulma.io/documentation/form/radio/

**Comment by timgavin** [comment]
Thanks for the heads up. Looks like Bulma inlines the radio elements by default, so `$form->radio()` and `$form->radio_inline()`; are basically the same. 

Regardless, I need to update the Bulma wrapper class to remove some elements that shouldn't be there with the radios, and will do that in the next push. In the mean time the following should work for you. Please let me know otherwise.

1. Open up `lib/wrappers/bulma.php`
2. Starting at line 50, replace this

```php
# build a checkbox
if ($data['type'] == 'checkbox' || $data['type'] == 'radio') {
    $return .= '<div class="field">' . $this->nl;
    $return .= '  <div class="control">' . $this->nl;
    $return .= '    <label class="checkbox">' . $this->nl;
    $return .=       $element . $this->nl;
    $return .=       $data['label'] . $this->nl;
    $return .= '    </label>' . $this->nl;
    $return .= '  </div>' . $this->nl;
    $return .= '</div>' . $this->nl;
    
    return $return;
    
}
```

with this

```php
# build a checkbox
if ($data['type'] == 'checkbox' || $data['type'] == 'radio') {
    if($data['type'] == 'checkbox') {
        $return .= '<div class="field">' . $this->nl;
    }
    $return .= '    <label class="'.$data['type'].'">' . $this->nl;
    $return .=       $element . $this->nl;
    $return .=       $data['label'] . $this->nl;
    $return .= '    </label>' . $this->nl;
    if($data['type'] == 'checkbox') {
        $return .= '  </div>' . $this->nl;
        $return .= '</div>' . $this->nl;
    }
    
    return $return;
    
}
```

**Comment by janstieler** [comment]
Hi,
thanks. This is a support which some big companies could cut a slice.
