### ISSUE TITLE
failed to install in laravel project

### ISSUE THREAD

**Issue by c0del1ar** [formr/Formr#163]
i try to install it in my laravel project use composer (`composer require formr/formr`) and it returns these errors.

![Screenshot_2023_0119_222208](https://user-images.githubusercontent.com/49186597/213482066-4ffe400d-3971-4da3-8257-e3ee6a53c984.jpg)

I used php@8.1.2 and all libraries are uptodate.

**Comment by timgavin** [comment]
Why would you want to use Formr with Laravel when Laravel already has really good form capabilities?

Regardless, if you want to use Formr with Laravel you'd need to rename the `Dropdowns` class (as the error suggests) and then update it everywhere else it's called. I wouldn't be surprised if other errors pop up after that, because Formr wasn't meant to be used this way.

I don't recommend this approach though, and can't offer any support. Good luck!
