### ISSUE TITLE
Three issues

### ISSUE THREAD

**Issue by Kukulkano** [formr/Formr#39]
I still think there are issues. Please see the below code and the produced output:
```
$form = new Formr();
echo $form->form_open("","","?p=customer");
echo $form->input_checkbox("chkReverse", "Reverse-Charge", "1");
echo $form->input_text("txtVAT", "VAT Amount");
echo $form->form_close();
```

Producing this output:
```
<form action="?p=customer" method="post" accept-charset="utf-8">

<label for="1">
	<input type="checkbox" name="chkReverse" id="1" value="1"> Reverse-Charge
</label>

<label for="">VAT Amount</label> 
<input type="text" name="txtVAT" class="input" id="txtVAT">

</form>
```
**Three problems here:**
1. The _checkbox_ _label_ is surrounding and the _text_ _label_ is on top. Inconsistent. Bad for CSS.
2. The _checkbox_ is not using the name as _id_. Instead, it uses the _value_. Bug?
3. The _text_ _label_ does not set the _for_ attribute to the used _id_. Bug?

**Comment by timgavin** [comment]
1. The label is wrapped around the checkbox so that the user can click the text and it will tick the box. This is common and good for user experience.

2. The value is used instead of the name because of instances where you may have multiple checkboxes with the same name.

3. This may be a bug. I'll look into it. Thanks!
