### ISSUE TITLE
Option value selected & session problem

### ISSUE THREAD

**Issue by manuelh78** [formr/Formr#42]
There a problem if selected item is in session values. There is no code for this case.

Besides, I had another problem, i don't use === because we need to be tolerant with keys. 
All the data stored in $ _POST are of type string.
But if the keys used when calling input_select() are of type integer or if a user set a value in $_Session, you may have a problem.

example :
````
$test = array(
            "0"=>"-",
            "1"=>"xxx", );

$test = array(
            0=>"-",
            1=>"xxx", );

echo $this->input_select('interet', 'xxxxxx','','','','','', $test);
````

here my code :
````
# user has entered a value in the 'values' argument
                    if ($this->session_values && $this->session && !empty($_SESSION[$this->session][$data['name']]) && $_SESSION[$this->session][$data['name']] == $key) {
                        $return .= $this->_t(2) . '<option value="' . $key . '" selected="selected">' . $value . '</option>' . $this->_nl(1);
                    }
                    elseif (!isset($_POST[$data['name']]) && $data['value'] == $key) {
//                    if (!isset($_POST[$data['name']]) && $data['value'] === $key) {
                        $return .= $this->_t(2) . '<option value="' . $key . '" selected="selected">' . $value . '</option>' . $this->_nl(1);
                    } else {
                        $return .= $this->_t(2) . '<option value="' . $key . '">' . $value . '</option>' . $this->_nl(1);
                    }
````

**Comment by JohnDBowne** [comment]
Hi, 
This is a 'me too' comment. I just updated the formr package on my test machine from a 2+ year hiatus. I've run into the same issue. The options array is a list of strings, that just happen to be numeric. But, with some debugging code in the _create_select function. 
```
foreach ($data['options'] as $key => $value) {
            #### jdb debug start
            error_log('key: type('.gettype($key).') --> '.$key);
            error_log('data[selected]: type('.gettype($data['selected']).') --> '.$data['selected']);
            #### jdb debug end

```
I get the following logging: 
```
key: type(integer) --> 201611, referer: http://johnbo... 
data[selected]: type(string) --> 201611, referer: http://johnbo...

```
The issue is that when I call the input_select function, I have to convert the selected field to an int, which will work for this element, which I can do (and it works). For the other selects on the page that have strings in the option value list, then the code seems to work.

This type changing by 'foreach' seems to be built into the language. It seems that formr either needs to force the key to be a string or switch back to "==" in place of "===" on line 3052 of class.formr.php

Thanks for the great package.
    johnbo

**Comment by timgavin** [comment]
I have tested both of the items mentioned and have seen no evidence of either not working. Using the following code, the select menu shows the `SESSION` value as the selected option.

```
<?php
session_start();

require_once 'Formr/class.formr.php';
$form = new Formr('bootstrap');

$form->session = 'myForm';

if($form->submitted()) {    
    $form->post('state');
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title>Formr</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <?php
            echo $form->messages();
            echo $form->form_open();
            $options = [
                'one' => 'one',
                'two' => 'two',
                'three' => 'three'
            ];
            echo $form->input_select('state','State','','','','','',$options);
            echo $form->input_button_submit();
            echo $form->form_close();
        ?>
    </div>
</body>
</html>
```

Furthermore, swapping out the `$options` array with integers produces the same result, the integer value is selected in the select menu, with or without using the `SESSION`.

```
$options = [
    1 => 1,
    2 => 2,
    3 => 3
];
```

**Comment by manuelh78** [comment]
Hi,

There is a problem with integers keys. I don't really understand how to use the session variables. If the form has not yet been posted, should we be able to use or reuse the session ?  

You can find my tests : 
````
session_start();

$form = new Formr('bootstrap');

$form->session = 'myForm2';


if (/*...*/ 1)
{
//force session value with a sql result 
    $_SESSION[$form->session]['books2'] = 'lorax';
    $_SESSION[$form->session]['books3'] = 'lorax';
}

/*if($form->submitted()) {    
    $r = $form->post('state');
    echo "r=$r<br>";    
}*/


var_dump($_SESSION);

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title>Formr</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <?php
            echo $form->messages();
            echo $form->form_open();
      
            // put our options into an array
            $options = array(
            'cat'    => 'The Cat in the Hat',
            'lorax'  => 'The Lorax',
            'yertle' => 'Yertle the Turtle',
            'grinch' => 'The Grinch Who Stole Christmas',
            'one'    => 'One',
            '2'      => 'Two', //my key will be a sql result!!!
            3      => 'Three',
            '2yertle'    => 'Yertle the Turtle 2' 
            
            );
            
            // print the array
            // notice that the 7th parameter is a default (selected) option
            // notice that the 8th parameter is our list of options
            echo $form->input_select('books', 'Books 1.1','','','','','yertle',$options); //OK
            echo $form->input_select('books', 'Books 1.2','','','','','grinch',$options);   //OK
            echo $form->input_select('books', 'Books 1.3','','','','','one',$options); //OK 
            
            echo $form->input_select('books', 'Books 1.4','','','','','2',$options); //dont work; i can't use an integer?
            echo $form->input_select('books', 'Books 1.5','','','','',2,$options); //OK!!! but array option is in a string
            
            echo $form->input_select('books', 'Books 1.6','','','','','3',$options); //dont work; i can't use an integer?
            echo $form->input_select('books', 'Books 1.7','','','','',3,$options); //OK!!!  
            
            echo $form->input_select('books', 'Books 1.8','','','','','2yertle',$options); //OK
            
            //Session are not full implemented in formr class ?
            echo $form->input_select('books2', 'Books 2.1','','','','','',$options); //dont work; session value is ignored
            echo $form->input_select('books3', 'Books 3.1','','','','','yertle',$options); //dont work; session value is ignored
            
             
            //echo $form->input_button_submit();
            echo $form->form_close();
        ?>
    </div>
</body>
</html>

````

**Comment by JohnDBowne** [comment]
I think that is issue that I was seeing is when there is some ambiguity about the type. In other areas, where all of the inputs are all ints or all strings, they work just fine. 

In my problem case, the option array was extracted from a database operation, which leaves everything as strings. In this case, the data is always stored as a string, even when it looks like an int. e.g. 201611. However, selected element input ended up getting converted to an int somewhere in the process. These values came from another input_select which started off as a string (also fetched from a database). 

In the end, the input_select function gets called with an array of strings, and a integer select value.  With the '===' in the code at (approximately) 3052, the comparison fails due to the need for an exact type match.

I'm just not sure if to use the library in the current condition works without having to coerce the variables to the right type. I believe that I've tried this while debugging, but it didn't fix the issue. In the end, I've modified the library code to use the '==' comparison. I really would like to avoid this, but I was not able to resolve the problem external to the function.

Thanks for your patience,
    johnbo
