### ISSUE TITLE
[Proposed Fix] Missing closing div tags which breaks inline-checkbox and inline-radio buttons

### ISSUE THREAD

**Issue by asule-star** [formr/Formr#80]
https://github.com/formr/Formr/blob/bba97c25b290becacae38028a44a5b33ce922a46/lib/wrappers/bootstrap.php#L73-L75

Noticed that the missing div closing tags on line 73 and 75 introduce this issue mentioned above.

Proposed Fix:
- close the div tags by appending to the end ( . '">' ) . Just like what was done on line 80.

**Comment by timgavin** [comment]
Please give me a sample of the code you're using to build the checkboxes or radios.

**Comment by asule-star** [comment]
Hey Tim,

Here's an example of my code:

========

$form = new Formr('bootstrap');
$form->session = 'people_session';
$form->required = 'first_name,last_name,email_address';

if($form->submit()) {
....
}

echo $form->messages();

$form->action = $_SERVER['REQUEST_URI'];
echo $form->form_open();
echo $form->csrf(1800);

// form input controls below
echo $form->create('First Name');
echo $form->label('','Is Active: ');
echo $form->input_radio_inline('is_active','Yes','yes','is_active');
echo $form->input_radio_inline('is_active','No','no','is_active');

// form input controls end here
$form->submit = 'Add New Person';
echo $form->input_submit();
echo $form->form_close();

==========



Thanks,

Abdulwahab
________________________________

**Comment by timgavin** [comment]
Thanks, this will be fixed in the next push.

Here's a way you can also speed up your form creation.

You don't need to use `$form->action = $_SERVER['REQUEST_URI'];` as it's already built into `$form->open()`

Using `$form->text()` would be better than using `$form->create()`, as `create()` creates an entire form, and `text()` creates a text input.

As of version 1.2.1 you no longer need to use `echo`, and you can use the new input aliases so you don't have to type `input_` before every form element.

Using `$form->submit_button()` allows you to add your button text directly into the method.

Adding an element name in parentheses to `$form->required` means all fields are required EXCEPT what's in the parentheses, which can greatly speed up form building.

You were also using the ID `is_active` on both radios. Instead, let Formr handle setting the ID so that each radio can be selected by clicking on the label text.

```php
$form->required = '(is_active)';

$form->open();
$form->csrf(1800);

$form->text('first_name', 'First Name');
$form->text('last_name', 'Last Name');
$form->email('email_address', 'Email Address');

$form->label('is_active','Is Active: ');
$form->radio_inline('is_active','Yes','yes');
$form->radio_inline('is_active','No','no');

$form->submit_button('Add New Person');
$form->close();
```
