### ISSUE TITLE
Q: Is it possible to define a multistep form where parts of the form will be defined and loaded by an Ajax Call?

### ISSUE THREAD

**Issue by bfiessinger** [formr/Formr#86]
I need to define parts (pages) of the form by previous answers and validate each part seperately, so is it possible to split a form in multiple parts, validate and evaluate values of each part and then send all parts together?

**Comment by timgavin** [comment]
I don't think Formr can do this without some custom scripting. However, one thing that comes to mind is to create several forms, give each one a unique ID and, if needed, use `$form->session` to store the values. Then when it's time to bring it all together just read the values from each `$form->session`.

This might get messy, but it sounds doable. Keep in mind that in order to keep track of which form was submitted you'll need to instantiate multiple forms and add a `$form->hidden` field with each form's ID, and then check to see if it was submitted.

In the following example, we're checking to see if `$form1` was submitted, but it doesn't matter which form we check because all Formr does is check to see if `$_SERVER['REQUEST_METHOD'] == 'POST'`, so any form name will do.

```php
$form1 = new Formr\Formr();
$form2 = new Formr\Formr();

if($form1->submitted()) {
    if($form1->post('form1Hidden')) {
        echo 'Form 1 was submitted';
    }
    if($form2->post('form2Hidden')) {
        echo 'Form 2 was submitted';
    }
}

$form1->id = 'Form1';
$form->session = 'Form1';
$form1->open();
$form1->hidden('form1Hidden','1');
$form1->submit_button('Submit Form 1');
$form1->close();

$form2->id = 'Form2';
$form2->session = 'Form2';
$form2->open();
$form2->hidden('form2Hidden','2');
$form2->submit_button('Submit Form 2');
$form2->close();
```

To get the `$_SESSION` values...

```php
$form1Values = $_SESSION['Form1'];
$form2Values = $_SESSION['Form2'];
```

##### Session Docs: https://formr.github.io/properties/#session
